version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./ex2.09.front.Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost/api

  backend:
    build:
      context: .
      dockerfile: ./ex2.09.back.Dockerfile
    environment:
      - REDIS_HOST=cache
      - POSTGRES_HOST=db

  cache:
    image: redis:alpine

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./psql_data:/var/lib/postgresql/data

  proxy:
    image: nginx:alpine
    volumes:
      - ./ex2.08.nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
